-- MySQL Script generated by MySQL Workbench
-- Tue Feb 16 09:47:10 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_grace
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_grace
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_grace` DEFAULT CHARACTER SET utf8 ;
USE `db_grace` ;


-- -----------------------------------------------------
-- Table `db_grace`.`tb_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_grace`.`tb_usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nick_name` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(16) NOT NULL,
  `email` VARCHAR(60) NULL,
  `celular` VARCHAR(14) NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `id_usuario_UNIQUE` (`id_usuario` ASC) VISIBLE,
  UNIQUE INDEX `nick_name_UNIQUE` (`nick_name` ASC) VISIBLE,
  UNIQUE INDEX `usuariocol_UNIQUE` (`celular` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_grace`.`tb_postagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_grace`.`tb_postagem` (
  `id_postagem` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(100) NOT NULL,
  `conteudo` VARCHAR(5000) BINARY NOT NULL,
  `tb_usuario_id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_postagem`, `tb_usuario_id_usuario`),
  UNIQUE INDEX `id_postagem_UNIQUE` (`id_postagem` ASC) VISIBLE,
  INDEX `fk_tb_postagem_tb_usuario_idx` (`tb_usuario_id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_tb_postagem_tb_usuario`
    FOREIGN KEY (`tb_usuario_id_usuario`)
    REFERENCES `db_grace`.`tb_usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_grace`.`tb_tema`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_grace`.`tb_tema` (
  `id_tema` INT NOT NULL AUTO_INCREMENT,
  `categoria` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`id_tema`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_grace`.`tb_postagem_has_tb_tema`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_grace`.`tb_postagem_has_tb_tema` (
  `tb_postagem_id_postagem` INT NOT NULL,
  `tb_postagem_tb_usuario_id_usuario` INT NOT NULL,
  `tb_tema_id_tema` INT NOT NULL,
  PRIMARY KEY (`tb_postagem_id_postagem`, `tb_postagem_tb_usuario_id_usuario`, `tb_tema_id_tema`),
  INDEX `fk_tb_postagem_has_tb_tema_tb_tema1_idx` (`tb_tema_id_tema` ASC) VISIBLE,
  INDEX `fk_tb_postagem_has_tb_tema_tb_postagem1_idx` (`tb_postagem_id_postagem` ASC, `tb_postagem_tb_usuario_id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_tb_postagem_has_tb_tema_tb_postagem1`
    FOREIGN KEY (`tb_postagem_id_postagem` , `tb_postagem_tb_usuario_id_usuario`)
    REFERENCES `db_grace`.`tb_postagem` (`id_postagem` , `tb_usuario_id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_postagem_has_tb_tema_tb_tema1`
    FOREIGN KEY (`tb_tema_id_tema`)
    REFERENCES `db_grace`.`tb_tema` (`id_tema`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;